name: Render

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Render list
        run: make render

      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          commit_message: Commit list
          commit_user_name: Idiomatic Rust Bot
          commit_user_email: bot@idiomatic.rs
          commit_author: Idiomatic Rust Bot <bot@idiomatic.rs>
